# Generated by Django 2.0.3 on 2018-03-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Кличка')),
                ('kind', models.CharField(choices=[('h', 'Хищник'), ('t', 'Травоядное'), ('v', 'Всеядный')], max_length=1, verbose_name='Вид')),
                ('img', models.ImageField(upload_to='animals', verbose_name='Изображение')),
            ],
        ),
    ]
