# Generated by Django 2.0.3 on 2018-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='animals', verbose_name='Изображение'),
        ),
    ]
